# Generated by Django 5.2.13 on 2026-04-18 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_update_product_unit_and_decimal_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fornecedor",
            field=models.CharField(
                blank=True,
                help_text="Fornecedor do material",
                max_length=150,
                null=True,
                verbose_name="fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="papel_gramatura",
            field=models.CharField(
                blank=True,
                help_text="Gramatura do papel (ex: 180g, 300g)",
                max_length=20,
                null=True,
                verbose_name="gramatura (g/m²)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("tecido", "Tecido"),
                    ("tinta", "Tinta"),
                    ("papel", "Papel"),
                    ("geral", "Geral (Aviamentos)"),
                ],
                default="geral",
                max_length=10,
                verbose_name="tipo de material",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantidade_baldes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número de baldes ou latas (para Tintas)",
                null=True,
                verbose_name="quantidade de baldes/latas",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantidade_rolos",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número de rolos (para Tecidos e Papéis)",
                null=True,
                verbose_name="quantidade de rolos",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tinta_tipo",
            field=models.CharField(
                blank=True,
                help_text="Ex: Acrílica, Têxtil, Serigráfica",
                max_length=50,
                null=True,
                verbose_name="tipo de tinta",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="total_litros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Volume total em litros (para Tintas)",
                max_digits=10,
                null=True,
                verbose_name="litros total",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="total_metragem",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Metragem total em metros (para Tecidos e Papéis)",
                max_digits=10,
                null=True,
                verbose_name="metragem total (m)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="inventory.category",
                verbose_name="categoria",
            ),
        ),
    ]
